# permissions for end users to edit declarations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: declaration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cript
    app.kubernetes.io/part-of: cript
    app.kubernetes.io/managed-by: kustomize
  name: declaration-editor-role
rules:
- apiGroups:
  - security.cript.dev
  resources:
  - declarations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.cript.dev
  resources:
  - declarations/status
  verbs:
  - get
