# permissions for end users to view scans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cript
    app.kubernetes.io/part-of: cript
    app.kubernetes.io/managed-by: kustomize
  name: scan-viewer-role
rules:
- apiGroups:
  - security.cript.dev
  resources:
  - scans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.cript.dev
  resources:
  - scans/status
  verbs:
  - get
