apiVersion: security.cript.dev/v1alpha1
kind: Scan
metadata:
  labels:
    app.kubernetes.io/name: scan
    app.kubernetes.io/instance: scan-sample
    app.kubernetes.io/part-of: cript
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cript
  name: scan-sample
spec:
  imageUri: "nginx@sha256:08bc36ad52474e528cc1ea3426b5e3f4bad8a130318e3140d6cfe29c8892c7ef"
  declarationRef:
    namespace: default
    name: declaration-sample
